// Generated by @wagmi/cli@1.0.0 on 5/21/2023 at 12:02:58 AM
// Generated by @wagmi/cli@1.0.0 on 5/21/2023 at 12:02:58 AM

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// GPURental
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const gpuRentalABI = [
  {
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [
      {name: '_paymentCoin', internalType: 'address', type: 'address'},
      {name: '_devAddress', internalType: 'address', type: 'address'},
    ],
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'approved',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'tokenId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'operator',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {name: 'approved', internalType: 'bool', type: 'bool', indexed: false},
    ],
    name: 'ApprovalForAll',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'previousOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'OwnershipTransferred',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {name: 'id', internalType: 'bytes32', type: 'bytes32', indexed: false},
      {
        name: 'pricePerHour',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'SetTemplatePrice',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {name: 'from', internalType: 'address', type: 'address', indexed: true},
      {name: 'to', internalType: 'address', type: 'address', indexed: true},
      {
        name: 'tokenId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'Transfer',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'tokenId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {name: 'user', internalType: 'address', type: 'address', indexed: true},
      {
        name: 'expires',
        internalType: 'uint64',
        type: 'uint64',
        indexed: false,
      },
    ],
    name: 'UpdateUser',
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'approve',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'owner', internalType: 'address', type: 'address'}],
    name: 'balanceOf',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: '', internalType: 'address', type: 'address'}],
    name: 'credits',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
      {name: 'amount', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'extendRental',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'tokenId', internalType: 'uint256', type: 'uint256'}],
    name: 'getApproved',
    outputs: [{name: '', internalType: 'address', type: 'address'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      {name: 'owner', internalType: 'address', type: 'address'},
      {name: 'operator', internalType: 'address', type: 'address'},
    ],
    name: 'isApprovedForAll',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'minRentalTime',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{name: '', internalType: 'string', type: 'string'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{name: '', internalType: 'address', type: 'address'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'tokenId', internalType: 'uint256', type: 'uint256'}],
    name: 'ownerOf',
    outputs: [{name: '', internalType: 'address', type: 'address'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{name: 'tokenId', internalType: 'uint256', type: 'uint256'}],
    name: 'pauseRental',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'templateId', internalType: 'bytes32', type: 'bytes32'},
      {name: 'amount', internalType: 'uint256', type: 'uint256'},
      {name: 'creditsToUse', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'rent',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'from', internalType: 'address', type: 'address'},
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'safeTransferFrom',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'from', internalType: 'address', type: 'address'},
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
      {name: 'data', internalType: 'bytes', type: 'bytes'},
    ],
    name: 'safeTransferFrom',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'operator', internalType: 'address', type: 'address'},
      {name: 'approved', internalType: 'bool', type: 'bool'},
    ],
    name: 'setApprovalForAll',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'id', internalType: 'bytes32', type: 'bytes32'},
      {name: 'pricePerHour', internalType: 'uint256', type: 'uint256'},
      {name: 'maxCount', internalType: 'uint8', type: 'uint8'},
    ],
    name: 'setTemplate',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
      {name: 'user', internalType: 'address', type: 'address'},
      {name: 'expires', internalType: 'uint64', type: 'uint64'},
    ],
    name: 'setUser',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'interfaceId', internalType: 'bytes4', type: 'bytes4'}],
    name: 'supportsInterface',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{name: '', internalType: 'string', type: 'string'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: '', internalType: 'bytes32', type: 'bytes32'}],
    name: 'templateInfo',
    outputs: [
      {name: 'id', internalType: 'bytes32', type: 'bytes32'},
      {name: 'pricePerHour', internalType: 'uint256', type: 'uint256'},
      {name: 'maxCount', internalType: 'uint8', type: 'uint8'},
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'tokenId', internalType: 'uint256', type: 'uint256'}],
    name: 'tokenURI',
    outputs: [{name: '', internalType: 'string', type: 'string'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'from', internalType: 'address', type: 'address'},
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'transferFrom',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{name: 'newOwner', internalType: 'address', type: 'address'}],
    name: 'transferOwnership',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'tokenId', internalType: 'uint256', type: 'uint256'}],
    name: 'userExpires',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
    name: 'userInfo',
    outputs: [
      {name: 'user', internalType: 'address', type: 'address'},
      {name: 'expires', internalType: 'uint64', type: 'uint64'},
      {name: 'templateId', internalType: 'bytes32', type: 'bytes32'},
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'tokenId', internalType: 'uint256', type: 'uint256'}],
    name: 'userOf',
    outputs: [{name: '', internalType: 'address', type: 'address'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'tokenId', internalType: 'uint256', type: 'uint256'}],
    name: 'verifyRental',
    outputs: [],
  },
] as const;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// TestToken
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const testTokenABI = [
  {
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [
      {name: '_name', internalType: 'string', type: 'string'},
      {name: '_symbol', internalType: 'string', type: 'string'},
    ],
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'spender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {name: 'from', internalType: 'address', type: 'address', indexed: true},
      {name: 'to', internalType: 'address', type: 'address', indexed: true},
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Transfer',
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      {name: 'owner', internalType: 'address', type: 'address'},
      {name: 'spender', internalType: 'address', type: 'address'},
    ],
    name: 'allowance',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'spender', internalType: 'address', type: 'address'},
      {name: 'amount', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'approve',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'account', internalType: 'address', type: 'address'}],
    name: 'balanceOf',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'decimals',
    outputs: [{name: '', internalType: 'uint8', type: 'uint8'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'spender', internalType: 'address', type: 'address'},
      {name: 'subtractedValue', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'decreaseAllowance',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{name: 'amount', internalType: 'uint256', type: 'uint256'}],
    name: 'giveMe',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'spender', internalType: 'address', type: 'address'},
      {name: 'addedValue', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'increaseAllowance',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{name: '', internalType: 'string', type: 'string'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{name: '', internalType: 'string', type: 'string'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'totalSupply',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'amount', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'transfer',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'from', internalType: 'address', type: 'address'},
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'amount', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'transferFrom',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
] as const;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IERC4907
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const ierc4907ABI = [
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'tokenId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
      {name: 'user', internalType: 'address', type: 'address', indexed: true},
      {
        name: 'expires',
        internalType: 'uint64',
        type: 'uint64',
        indexed: false,
      },
    ],
    name: 'UpdateUser',
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
      {name: 'user', internalType: 'address', type: 'address'},
      {name: 'expires', internalType: 'uint64', type: 'uint64'},
    ],
    name: 'setUser',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'tokenId', internalType: 'uint256', type: 'uint256'}],
    name: 'userExpires',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'tokenId', internalType: 'uint256', type: 'uint256'}],
    name: 'userOf',
    outputs: [{name: '', internalType: 'address', type: 'address'}],
  },
] as const;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Ownable
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const ownableABI = [
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'previousOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'newOwner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
    ],
    name: 'OwnershipTransferred',
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'owner',
    outputs: [{name: '', internalType: 'address', type: 'address'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{name: 'newOwner', internalType: 'address', type: 'address'}],
    name: 'transferOwnership',
    outputs: [],
  },
] as const;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ERC20
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const erc20ABI = [
  {
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [
      {name: 'name_', internalType: 'string', type: 'string'},
      {name: 'symbol_', internalType: 'string', type: 'string'},
    ],
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'spender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {name: 'from', internalType: 'address', type: 'address', indexed: true},
      {name: 'to', internalType: 'address', type: 'address', indexed: true},
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Transfer',
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      {name: 'owner', internalType: 'address', type: 'address'},
      {name: 'spender', internalType: 'address', type: 'address'},
    ],
    name: 'allowance',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'spender', internalType: 'address', type: 'address'},
      {name: 'amount', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'approve',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'account', internalType: 'address', type: 'address'}],
    name: 'balanceOf',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'decimals',
    outputs: [{name: '', internalType: 'uint8', type: 'uint8'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'spender', internalType: 'address', type: 'address'},
      {name: 'subtractedValue', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'decreaseAllowance',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'spender', internalType: 'address', type: 'address'},
      {name: 'addedValue', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'increaseAllowance',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{name: '', internalType: 'string', type: 'string'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{name: '', internalType: 'string', type: 'string'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'totalSupply',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'amount', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'transfer',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'from', internalType: 'address', type: 'address'},
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'amount', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'transferFrom',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
] as const;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ERC721
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const erc721ABI = [
  {
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [
      {name: 'name_', internalType: 'string', type: 'string'},
      {name: 'symbol_', internalType: 'string', type: 'string'},
    ],
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'approved',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'tokenId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'operator',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {name: 'approved', internalType: 'bool', type: 'bool', indexed: false},
    ],
    name: 'ApprovalForAll',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {name: 'from', internalType: 'address', type: 'address', indexed: true},
      {name: 'to', internalType: 'address', type: 'address', indexed: true},
      {
        name: 'tokenId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'Transfer',
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'approve',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'owner', internalType: 'address', type: 'address'}],
    name: 'balanceOf',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'tokenId', internalType: 'uint256', type: 'uint256'}],
    name: 'getApproved',
    outputs: [{name: '', internalType: 'address', type: 'address'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      {name: 'owner', internalType: 'address', type: 'address'},
      {name: 'operator', internalType: 'address', type: 'address'},
    ],
    name: 'isApprovedForAll',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{name: '', internalType: 'string', type: 'string'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'tokenId', internalType: 'uint256', type: 'uint256'}],
    name: 'ownerOf',
    outputs: [{name: '', internalType: 'address', type: 'address'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'from', internalType: 'address', type: 'address'},
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'safeTransferFrom',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'from', internalType: 'address', type: 'address'},
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
      {name: 'data', internalType: 'bytes', type: 'bytes'},
    ],
    name: 'safeTransferFrom',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'operator', internalType: 'address', type: 'address'},
      {name: 'approved', internalType: 'bool', type: 'bool'},
    ],
    name: 'setApprovalForAll',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'interfaceId', internalType: 'bytes4', type: 'bytes4'}],
    name: 'supportsInterface',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{name: '', internalType: 'string', type: 'string'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'tokenId', internalType: 'uint256', type: 'uint256'}],
    name: 'tokenURI',
    outputs: [{name: '', internalType: 'string', type: 'string'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'from', internalType: 'address', type: 'address'},
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'transferFrom',
    outputs: [],
  },
] as const;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IERC20
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const ierc20ABI = [
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'spender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {name: 'from', internalType: 'address', type: 'address', indexed: true},
      {name: 'to', internalType: 'address', type: 'address', indexed: true},
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Transfer',
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      {name: 'owner', internalType: 'address', type: 'address'},
      {name: 'spender', internalType: 'address', type: 'address'},
    ],
    name: 'allowance',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'spender', internalType: 'address', type: 'address'},
      {name: 'amount', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'approve',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'account', internalType: 'address', type: 'address'}],
    name: 'balanceOf',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'totalSupply',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'amount', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'transfer',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'from', internalType: 'address', type: 'address'},
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'amount', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'transferFrom',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
] as const;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IERC721
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const ierc721ABI = [
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'approved',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'tokenId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'operator',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {name: 'approved', internalType: 'bool', type: 'bool', indexed: false},
    ],
    name: 'ApprovalForAll',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {name: 'from', internalType: 'address', type: 'address', indexed: true},
      {name: 'to', internalType: 'address', type: 'address', indexed: true},
      {
        name: 'tokenId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'Transfer',
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'approve',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'owner', internalType: 'address', type: 'address'}],
    name: 'balanceOf',
    outputs: [{name: 'balance', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'tokenId', internalType: 'uint256', type: 'uint256'}],
    name: 'getApproved',
    outputs: [{name: 'operator', internalType: 'address', type: 'address'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      {name: 'owner', internalType: 'address', type: 'address'},
      {name: 'operator', internalType: 'address', type: 'address'},
    ],
    name: 'isApprovedForAll',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'tokenId', internalType: 'uint256', type: 'uint256'}],
    name: 'ownerOf',
    outputs: [{name: 'owner', internalType: 'address', type: 'address'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'from', internalType: 'address', type: 'address'},
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'safeTransferFrom',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'from', internalType: 'address', type: 'address'},
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
      {name: 'data', internalType: 'bytes', type: 'bytes'},
    ],
    name: 'safeTransferFrom',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'operator', internalType: 'address', type: 'address'},
      {name: '_approved', internalType: 'bool', type: 'bool'},
    ],
    name: 'setApprovalForAll',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'interfaceId', internalType: 'bytes4', type: 'bytes4'}],
    name: 'supportsInterface',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'from', internalType: 'address', type: 'address'},
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'transferFrom',
    outputs: [],
  },
] as const;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IERC721Receiver
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const ierc721ReceiverABI = [
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'operator', internalType: 'address', type: 'address'},
      {name: 'from', internalType: 'address', type: 'address'},
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
      {name: 'data', internalType: 'bytes', type: 'bytes'},
    ],
    name: 'onERC721Received',
    outputs: [{name: '', internalType: 'bytes4', type: 'bytes4'}],
  },
] as const;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ERC165
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const erc165ABI = [
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'interfaceId', internalType: 'bytes4', type: 'bytes4'}],
    name: 'supportsInterface',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
] as const;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IERC165
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const ierc165ABI = [
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'interfaceId', internalType: 'bytes4', type: 'bytes4'}],
    name: 'supportsInterface',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
] as const;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IERC20Metadata
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const ierc20MetadataABI = [
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'spender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {name: 'from', internalType: 'address', type: 'address', indexed: true},
      {name: 'to', internalType: 'address', type: 'address', indexed: true},
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Transfer',
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      {name: 'owner', internalType: 'address', type: 'address'},
      {name: 'spender', internalType: 'address', type: 'address'},
    ],
    name: 'allowance',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'spender', internalType: 'address', type: 'address'},
      {name: 'amount', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'approve',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'account', internalType: 'address', type: 'address'}],
    name: 'balanceOf',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'decimals',
    outputs: [{name: '', internalType: 'uint8', type: 'uint8'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{name: '', internalType: 'string', type: 'string'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{name: '', internalType: 'string', type: 'string'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'totalSupply',
    outputs: [{name: '', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'amount', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'transfer',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'from', internalType: 'address', type: 'address'},
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'amount', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'transferFrom',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
] as const;

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IERC721Metadata
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const ierc721MetadataABI = [
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'approved',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'tokenId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'operator',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {name: 'approved', internalType: 'bool', type: 'bool', indexed: false},
    ],
    name: 'ApprovalForAll',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {name: 'from', internalType: 'address', type: 'address', indexed: true},
      {name: 'to', internalType: 'address', type: 'address', indexed: true},
      {
        name: 'tokenId',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'Transfer',
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'approve',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'owner', internalType: 'address', type: 'address'}],
    name: 'balanceOf',
    outputs: [{name: 'balance', internalType: 'uint256', type: 'uint256'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'tokenId', internalType: 'uint256', type: 'uint256'}],
    name: 'getApproved',
    outputs: [{name: 'operator', internalType: 'address', type: 'address'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      {name: 'owner', internalType: 'address', type: 'address'},
      {name: 'operator', internalType: 'address', type: 'address'},
    ],
    name: 'isApprovedForAll',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'name',
    outputs: [{name: '', internalType: 'string', type: 'string'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'tokenId', internalType: 'uint256', type: 'uint256'}],
    name: 'ownerOf',
    outputs: [{name: 'owner', internalType: 'address', type: 'address'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'from', internalType: 'address', type: 'address'},
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'safeTransferFrom',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'from', internalType: 'address', type: 'address'},
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
      {name: 'data', internalType: 'bytes', type: 'bytes'},
    ],
    name: 'safeTransferFrom',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'operator', internalType: 'address', type: 'address'},
      {name: '_approved', internalType: 'bool', type: 'bool'},
    ],
    name: 'setApprovalForAll',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'interfaceId', internalType: 'bytes4', type: 'bytes4'}],
    name: 'supportsInterface',
    outputs: [{name: '', internalType: 'bool', type: 'bool'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'symbol',
    outputs: [{name: '', internalType: 'string', type: 'string'}],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{name: 'tokenId', internalType: 'uint256', type: 'uint256'}],
    name: 'tokenURI',
    outputs: [{name: '', internalType: 'string', type: 'string'}],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      {name: 'from', internalType: 'address', type: 'address'},
      {name: 'to', internalType: 'address', type: 'address'},
      {name: 'tokenId', internalType: 'uint256', type: 'uint256'},
    ],
    name: 'transferFrom',
    outputs: [],
  },
] as const;
